# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c2613fd31b965bd59c6fdb1d4c813bff596835b7900363aff2d24c3445bdeec9149ef7e64b92bbfe9feac068892e6d9460cc42ee769fbc8643c0af2b957c44

test:
  secret_key_base: e6f309b0671e32c449ddf7ababbdb89ee341f03e49428ccc016907613444c4be068a8a54c6508a1a94288e92e631d04dc7e4f25b5429eca28ebe35d83e1053d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
